name: build and test
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-code-coverage
