name: build and test
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-code-coverage
    - name: Test coverage
      uses: mattpolzin/swift-codecov-action@0.7.5
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4.3.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
